### ISSUE TITLE
Debug and build files version controlled

### ISSUE THREAD

**Issue by Lynx-At0Mic** [Stevie-Goodman/CMP1903M-Assessment1#13]
Files in `./bin` and `./obj` are version controlled and cause unnecessary commits. Add a `.gitignore` file to the project directory with the gitignore rules from the [VisualStudio gitignore](https://github.com/github/gitignore/blob/master/VisualStudio.gitignore). This should keep your working tree clean from generated files during development.

**Comment by Stevie-Goodman** [comment]
@Lynx-At0Mic, figured that was the case but Rider was hiding the "Add to .gitignore" button.
Copied the list from the link.

I'm working through your pull request and I'll have a review posted by Monday.
You don't have to, but a review of Report.cs would be appreciated.
Thanks.
